apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: nextapp
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/itegmark/nextjs-k8s-config
  branch: master